search_rules:
#    start-time: 2020-01-06
#    end-time: 2020-01-10
    query: laschet has:hashtags

search_params:
    results-per-call: 10
    max-tweets: 10
    tweet-fields: id,created_at,author_id,text,public_metrics
    user-fields: username
    expansions: author_id

output_params:
    save_file: True
    filename_prefix: test
    results_per_file: 100000
    output_format: a
